# Generated by Django 4.1.2 on 2022-10-12 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phones', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='slug',
            field=models.SlugField(max_length=255, verbose_name='URL'),
        ),
    ]
